name: Programmers & Baekjoon profile checker

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -O /tmp/chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/linux64/chrome-linux64.zip
        sudo unzip /tmp/chrome-linux64.zip -d /opt/google/chrome
        sudo rm -f /usr/bin/google-chrome
        sudo ln -s /opt/google/chrome/chrome /usr/bin/google-chrome

    - name: Install ChromeDriver
      run: |
        wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/linux64/chromedriver-linux64.zip
        sudo unzip /tmp/chromedriver.zip -d /opt/chrome-linux64/
        sudo ln -s /opt/chrome-linux64/chromedriver /usr/local/bin/chromedriver
        chromedriver --version

    - name: Set up jdk17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'gradle'

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: programmersTracker

    - name: Run the application
      run: java -jar ./build/libs/programmersTracker-0.0.1-SNAPSHOT.jar
      working-directory: programmersTracker
      env:
        PROGRAMMERS_ID: ${{ secrets.PROGRAMMERS_ID }}
        PROGRAMMERS_PW: ${{ secrets.PROGRAMMERS_PW }}
        BAEKJOON_ID: ${{ secrets.BAEKJOON_ID }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update programmers & baekjoon profile'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
